replicaCount: 2

image:
  repository: billing-service
  tag: "local"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

env:
  SERVICE_NAME: billing-service

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
